font_family       Fira Code
bold_font         auto
italic_font       auto
bolc_italic_font  auto

map ctrl+shift+enter launch --cwd current --type os-window

enable_audio_bell no

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
# include current-theme.conf
include gruv.conf
# END_KITTY_THEME
